/* THE BEFORE-YOU-ACCEPT NOTICES (ACCEPT-PAGE-02). GENERATED — never edit these strings by hand.

   LIGHTING_EN is READY-4's lighting paragraph (Bridge/SITE-ROWS-READY-01/READY-4-status-page-disclosures.md),
   word for word: its bold lead and the sentence after it. Shown when env.NOTICE_LIGHTING is "true" (the default).

   NOTICE_53255 is the disclosure statement of Texas Property Code section 53.255(b), copied from the statute
   itself: https://statutes.capitol.texas.gov/Docs/PR/htm/PR.53.htm#53.255 (served from the Legislature's
   https://tcss.legis.texas.gov/resources/PR/htm/PR.53.htm), read 2026-09-23T17:22:44Z. One string per
   paragraph, exactly as the statute prints it, with only the statute's own quotation marks around the quoted
   statement removed. Shown only when env.NOTICE_53255 is "true" (default "false" — his one-word call). */

export const LIGHTING_EN = {
 "lead": "Light.",
 "text": "Strong light that rakes along a wall or ceiling — a window late in the day, or a fixture mounted right on the surface — shows up small differences in any repaired surface, including ours. We judge a repair the way the painting trade judges one: from three feet away, in the room's normal light. If a surface is one where a patch will always catch that raking light, we tell you that before we start, not after."
};

export const NOTICE_53255 = [
 "KNOW YOUR RIGHTS AND RESPONSIBILITIES UNDER THE LAW.  You are about to enter into a transaction to build a new home or remodel existing residential property.  Texas law requires your contractor to provide you with this brief overview of some of your rights, responsibilities, and risks in this transaction.",
 "CONVEYANCE TO CONTRACTOR NOT REQUIRED.  Your contractor may not require you to convey your real property to your contractor as a condition to the agreement for the construction of improvements on your property.",
 "KNOW YOUR CONTRACTOR.  Before you enter into your agreement for the construction of improvements to your real property, make sure that you have investigated your contractor.  Obtain and verify references from other people who have used the contractor for the type and size of construction project on your property.",
 "GET IT IN WRITING.  Make sure that you have a written agreement with your contractor that includes: (1)  a description of the work the contractor is to perform; (2)  the required or estimated time for completion of the work; (3)  the cost of the work or how the cost will be determined; and (4)  the procedure and method of payment, including provisions for statutory reservation of funds and conditions for final payment.  If your contractor made a promise, warranty, or representation to you concerning the work the contractor is to perform, make sure that promise, warranty, or representation is specified in the written agreement.  An oral promise that is not included in the written agreement may not be enforceable under Texas law.",
 "READ BEFORE YOU SIGN.  Do not sign any document before you have read and understood it.  NEVER SIGN A DOCUMENT THAT INCLUDES AN UNTRUE STATEMENT.  Take your time in reviewing documents.  If you borrow money from a lender to pay for the improvements, you are entitled to have the loan closing documents furnished to you for review at least one business day before the closing.  Do not waive this requirement unless a bona fide emergency or another good cause exists, and make sure you understand the documents before you sign them.  If you fail to comply with the terms of the documents, you could lose your property.  You are entitled to have your own attorney review any documents.  If you have any question about the meaning of a document, consult an attorney.",
 "GET A LIST OF SUBCONTRACTORS AND SUPPLIERS. Before construction commences, your contractor is required to provide you with a list of the subcontractors and suppliers the contractor intends to use on your project.  Your contractor is required to supply updated information on any subcontractors and suppliers added after the list is provided.  Your contractor is not required to supply this information if you sign a written waiver of your rights to receive this information.",
 "MONITOR THE WORK. Lenders and governmental authorities may inspect the work in progress from time to time for their own purposes.  These inspections are not intended as quality control inspections.  Quality control is a matter for you and your contractor.  To ensure that your home is being constructed in accordance with your wishes and specifications, you should inspect the work yourself or have your own independent inspector review the work in progress.",
 "MONITOR PAYMENTS. If you use a lender, your lender is required to provide you with a periodic statement showing the money disbursed by the lender from the proceeds of your loan.  Each time your contractor requests payment from you or your lender for work performed, your contractor is also required to furnish you with a disbursement statement that lists the name and address of each subcontractor or supplier that the contractor intends to pay from the requested funds. Review these statements and make sure that the money is being properly disbursed.",
 "CLAIMS BY SUBCONTRACTORS AND SUPPLIERS. Under Texas law, if a subcontractor or supplier who furnishes labor or materials for the construction of improvements on your property is not paid, you may become liable and your property may be subject to a lien for the unpaid amount, even if you have not contracted directly with the subcontractor or supplier.  To avoid liability, you should take the following actions:",
 "(1)  If you receive a written notice from a subcontractor or supplier, you should withhold payment from your contractor for the amount of the claim stated in the notice until the dispute between your contractor and the subcontractor or supplier is resolved.  If your lender is disbursing money directly to your contractor, you should immediately provide a copy of the notice to your lender and instruct the lender to withhold payment in the amount of the claim stated in the notice.  If you continue to pay the contractor after receiving the written notice without withholding the amount of the claim, you may be liable and your property may be subject to a lien for the amount you failed to withhold.",
 "(2)  During construction and for 30 days after final completion, termination, or abandonment of the contract by the contractor, you should reserve or cause your lender to reserve 10 percent of the amount of payments made for the work performed by your contractor.   If you choose not to reserve the 10 percent for at least 30 days after final completion, termination, or abandonment of the contract by the contractor and if a valid claim is timely made by a claimant and your contractor fails to pay the claim, you may be personally liable and your property may be subject to a lien up to the amount that you failed to reserve.",
 "If a claim is not paid within a certain time period, the claimant is required to file a mechanic's lien affidavit in the real property records in the county where the property is located.  A mechanic's lien affidavit is not a lien on your property, but the filing of the affidavit could result in a court imposing a lien on your property if the claimant is successful in litigation to enforce the lien claim.",
 "SOME CLAIMS MAY NOT BE VALID. When you receive a written notice of a claim or when a mechanic's lien affidavit is filed on your property, you should know your legal rights and responsibilities regarding the claim.  Not all claims are valid.  A notice of a claim by a subcontractor or supplier is required to be sent, and the mechanic's lien affidavit is required to be filed, within strict time periods.  The notice and the affidavit must contain certain information.  All claimants may not fully comply with the legal requirements to collect on a claim.  If you have paid the contractor in full before receiving a notice of a claim and have withheld the 10 percent of the contract price or value of work, you may not be liable for that claim.  Accordingly, you should consult your attorney when you receive a written notice of a claim to determine the true extent of your liability or potential liability for that claim.",
 "OBTAIN A LIEN RELEASE AND A BILLS-PAID AFFIDAVIT. When you receive a notice of claim, do not release withheld funds without obtaining a signed and notarized release of lien and claim from the claimant.  You can also reduce the risk of having a claim filed by a subcontractor or supplier by requiring as a condition of each payment made by you or your lender that your contractor furnish you with an affidavit stating that all bills have been paid.  Under Texas law, on final completion of the work and before final payment, the contractor is required to furnish you with an affidavit stating that all bills have been paid.  If the contractor discloses any unpaid bill in the affidavit, you should withhold payment in the amount of the unpaid bill until you receive a waiver of lien or release from that subcontractor or supplier.",
 "OBTAIN TITLE INSURANCE PROTECTION. You may be able to obtain a title insurance policy to insure that the title to your property and the existing improvements on your property are free from liens claimed by subcontractors and suppliers.  If your policy is issued before the improvements are completed and covers the value of the improvements to be completed, you should obtain, on the completion of the improvements and as a condition of your final payment, a 'completion of improvements' policy endorsement.  This endorsement will protect your property from liens claimed by subcontractors and suppliers that may arise from the date the original title policy is issued to the date of the endorsement."
];

/* sha256 of the texts above, joined by "\n", so a reading can prove nothing drifted. */
export const LIGHTING_SHA256 = "4e7fa103d6814a179bb24d81762b6c8e2cbf69df29f5bab1c7ad89e42deb4e57";
export const NOTICE_53255_SHA256 = "d5c0d4c8feb0a0452196eece55b44b4a0251ae4699f519fcd5bc0aeed5684b9b";
