/* THE CUSTOMER'S PAGE — ITS WORDS (ACCEPT-PAGE-02). Kept apart from page.js so the tests can read the same
   table the page renders from (page.js imports the book; this file imports nothing). */

/* Every fixed string on the page, in both languages. The Spanish is ours; every line goes to his local reviewer
   in the close, with its English beside it. {x} is filled in; nothing else is. No phone number, address or email
   of anyone; nothing R37 §5 rules out of a scheduling message; no materials (R38); neither of the two words R33
   keeps off everything this company prints. Suite I greps every page it renders for all of it. */
export const WORDS = {
  en: {
    title: 'Your quote from Umbra Domus',
    hi_name: "Hi {name}, here's your price.",
    hi: "Hi, here's your price.",
    h_work: "What I'll do",
    h_price: 'Price',
    h_when: 'When',
    when: '{day} · arrival between {window}',
    pick_legend: 'Pick your time',
    pick_error: 'Pick one of the times.',
    hold_one: 'Held for you until {at}.',
    hold_two: 'Held for you until {at}.',
    hold_ended_one: "My hold on this time has ended, but it's still open.",
    hold_ended_two: "My hold on these times has ended, but they're still open.",
    h_notices: 'Before you accept',
    statute_intro: 'The disclosure statement Texas Property Code §53.255 asks me to give you before you agree to the work:',
    accept: 'Accept & confirm',
    none: 'None of these times work',
    none_one: "This time doesn't work",
    small: 'Accepting books this visit at the price above. Questions? Reply to my text.',
    h_taken: 'That time was just booked.',
    taken_other: 'This time is still open:',
    taken_none: "Reply to my text and I'll find you another time.",
    h_too_close: 'This time is too close for me to prepare.',
    too_close: "Reply to my text and I'll find another.",
    h_booked: "You're booked.",
    booked_window: 'arrival between {window}',
    booked_confirm: "I'll text you to confirm.",
    h_updating: "I'm updating this quote.",
    updating: "You'll get a new text from me shortly.",
    h_replaced: 'This quote was replaced.',
    replaced: 'Use the link in my latest text.',
    h_withdrawn: 'This quote was withdrawn.',
    withdrawn: 'Reply to my text with any questions.',
    h_received: 'Got it.',
    received: "I'll text you some other times.",
    h_not_valid: "This link isn't valid.",
    not_valid: 'Check the link in my text, or reply to it.',
    h_forbidden: "This didn't come from my page.",
    forbidden: 'Open the link in my text again, or reply to it.',
    questions: 'Questions? Reply to my text.',
    /* QUOTE-PAGE-03: the new look. `when`, `booked_window` and `title` leave the visible page by design (the day
       and when_line sit on two lines; BOOKED uses when_line; h1_quote is the heading and `title` stays the <title>). */
    h1_quote: 'Your quote',
    steps: ['Received', 'Quoted', 'Scheduled', 'Done'],
    steps_label: 'Where your request stands',
    lbl_visit: 'Your visit',
    when_line: 'Arrival between {window}',
    law_title: 'Your rights under Texas law',
    law_hint: 'Tap to read',
    add_calendar: 'Add to my calendar',
    ics_title: 'Umbra Domus visit (arrival window)',
    ics_desc: 'Arrival between {window}. Questions? Reply to my text.',
    /* road W (2026-09-26): options of one or two visits. A card lists every day of its option ("Mon 9/28, arriving
       8–10 AM" / "then Tue 9/29, arriving 11 AM–1 PM"); Accept sits right under the choice; the step list folds to
       one line; the trust lines and the notices sit below the button; the hold is hold_until, the one the Flux shows.
       `h_notices` is now the heading of that lower part, so it no longer says "before". */
    h_notices_below: 'Good to know',
    pick_legend_pair: 'Pick your days',
    card_first: '{day}, arriving {span}',
    card_then: 'then {day}, arriving {span}',
    ticket_arrive: 'Arriving {span}',
    ticket_then: 'then',
    lbl_visits: 'Your visits',
    work_hint_one: '1 step · tap to see it',
    work_hint: '{n} steps · tap to see them',
    none_pair: "These days don't work",
    small_pair: 'Accepting books both visits at the price above. Questions? Reply to my text.',
    h_taken_pair: 'One of those days was just booked.',
    taken_other_pair: 'These days are still open:',
    booked_done: 'Nothing else to do.',
    booked_small: 'Need to move it, or have a question? Reply to my text.',
    /* SITE-FIX-03: the end of the booked line. The FLUX sends that text (FLUX-FIX-16), never this page —
       the page only promises it. road XW's one voice: Drew speaking, as "Reply to my text." above does. */
    booked_promise: "I'll text you the day before.",
    /* road XW (2026-09-26): ONE VOICE — Drew speaking ("I", "my text") on every line of the English page; the step count
       the Flux's plan has (step_count), with the steps the list does not name counted in one line; each visit's length
       when the Flux sends it (visit_minutes); "with your paint" when they said they have it; the year their house was
       built, one optional box above Accept. */
    work_more_one: 'Plus 1 smaller step along the way.',
    work_more: 'Plus {n} smaller steps along the way.',
    visit_len: ' · {len}',
    paint_theirs: 'Painted with your paint.',
    year_label: 'What year was your house built?',
    year_hint: "Optional. It tells me what's in your walls.",
  },
  es: {
    title: 'Su cotización de Umbra Domus',
    hi_name: 'Hola, {name}: este es su precio.',
    hi: 'Hola: este es su precio.',
    h_work: 'Lo que haremos',
    h_price: 'Precio',
    h_when: 'Cuándo',
    when: '{day} · llegada entre {window}',
    pick_legend: 'Elija su horario',
    pick_error: 'Elija uno de los horarios.',
    hold_one: 'Le apartamos este horario hasta el {at}.',
    hold_two: 'Le apartamos estos horarios hasta el {at}.',
    hold_ended_one: 'Ya no le estamos apartando este horario, pero sigue disponible.',
    hold_ended_two: 'Ya no le estamos apartando estos horarios, pero siguen disponibles.',
    h_notices: 'Antes de aceptar',
    statute_intro: 'La declaración que la sección 53.255 del Código de Propiedad de Texas nos pide entregarle antes de que acepte el trabajo (el texto de la ley está en inglés):',
    accept: 'Aceptar y confirmar',
    none: 'Ninguno de estos horarios me acomoda',
    none_one: 'Este horario no me acomoda',
    small: 'Al aceptar, queda programada esta visita al precio de arriba. ¿Preguntas? Responda a nuestro mensaje de texto.',
    h_taken: 'Ese horario ya se ocupó.',
    taken_other: 'Este horario sigue disponible:',
    taken_none: 'Responda a nuestro mensaje de texto y le buscaremos otro horario.',
    h_too_close: 'Este horario ya está muy cerca para prepararnos.',
    too_close: 'Responda a nuestro mensaje de texto y le buscaremos otro.',
    h_booked: 'Su visita quedó programada.',
    booked_window: 'Llegada entre {window}',
    booked_confirm: 'Le enviaremos un mensaje de texto para confirmar.',
    h_updating: 'Estamos actualizando esta cotización.',
    updating: 'En breve le enviaremos un nuevo mensaje de texto.',
    h_replaced: 'Esta cotización fue reemplazada.',
    replaced: 'Use el enlace de nuestro mensaje de texto más reciente.',
    h_withdrawn: 'Esta cotización fue retirada.',
    withdrawn: 'Si tiene preguntas, responda a nuestro mensaje de texto.',
    h_received: 'Entendido.',
    received: 'Le enviaremos otros horarios por mensaje de texto.',
    h_not_valid: 'Este enlace no es válido.',
    not_valid: 'Revise el enlace de nuestro mensaje de texto o respóndanos.',
    h_forbidden: 'Esto no se envió desde nuestra página.',
    forbidden: 'Vuelva a abrir el enlace de nuestro mensaje de texto o respóndanos.',
    questions: '¿Preguntas? Responda a nuestro mensaje de texto.',
    /* QUOTE-PAGE-03, from Drew's RGV Spanish researcher (Bridge/SUPE/RESEARCH-SPANISH-RGV-2026-09-23/). ics_desc has
       no period after {window}: its "a.m."/"p.m." ends the sentence. */
    h1_quote: 'Su cotización',
    steps: ['Recibido', 'Cotizado', 'Programado', 'Terminado'],
    steps_label: 'En qué paso va su solicitud',
    lbl_visit: 'Su visita',
    when_line: 'Llegada entre {window}',
    law_title: 'Sus derechos según la ley de Texas',
    law_hint: 'Toque para leer',
    add_calendar: 'Agregar a mi calendario',
    ics_title: 'Visita de Umbra Domus (horario de llegada)',
    ics_desc: 'Llegada entre {window} ¿Preguntas? Responda a nuestro mensaje de texto.',
    /* road W (2026-09-26): the same changes as the English, for his reviewer. {span} is "las 8 y las 10 a.m.". */
    h_notices_below: 'Bueno saberlo',
    pick_legend_pair: 'Elija sus días',
    card_first: '{day}, llegada entre {span}',
    card_then: 'luego, {day}, llegada entre {span}',
    ticket_arrive: 'Llegada entre {span}',
    ticket_then: 'luego,',
    lbl_visits: 'Sus visitas',
    work_hint_one: '1 paso · toque para verlo',
    work_hint: '{n} pasos · toque para verlos',
    none_pair: 'Estos días no me acomodan',
    small_pair: 'Al aceptar, quedan programadas las dos visitas al precio de arriba. ¿Preguntas? Responda a nuestro mensaje de texto.',
    h_taken_pair: 'Uno de esos días ya se ocupó.',
    taken_other_pair: 'Estos días siguen disponibles:',
    booked_done: 'No tiene que hacer nada más.',
    booked_small: '¿Necesita cambiarla o tiene preguntas? Responda a nuestro mensaje de texto.',
    booked_promise: 'Le enviaremos un mensaje de texto el día anterior.',
    /* road XW (2026-09-26): the same new lines, for his reviewer. The Spanish page keeps its own voice ("nosotros"). */
    work_more_one: 'Y 1 paso menor durante el trabajo.',
    work_more: 'Y {n} pasos menores durante el trabajo.',
    visit_len: ' · {len}',
    paint_theirs: 'Pintado con su pintura.',
    year_label: '¿En qué año se construyó su casa?',
    year_hint: 'Opcional. Nos dice qué hay dentro de sus paredes.',
  },
};

/* road XW (2026-09-26): the "Light." paragraph cut to one line, in his voice — what the English page shows now. READY-4's
   full paragraph (notices.js LIGHTING_EN) is kept as it was, with its sha256. The Spanish page keeps LIGHTING_ES (below,
   reviewed) until his reviewer reads the one-line version: es here is that proposal, not shown yet. */
export const LIGHT_SHORT = {
  en: { lead: 'Light.', text: "Low light across a wall shows small marks on any repair, so I judge mine from 3 feet in the room's normal light." },
  es: { lead: 'Luz.', text: 'La luz baja que cruza una pared deja ver pequeñas marcas en cualquier reparación; por eso la juzgamos a tres pies, con la luz normal del cuarto.' },
};

/* READY-4's lighting paragraph, in Spanish (ours — for his reviewer). The English is notices.js, word for word. */
export const LIGHTING_ES = {
  lead: 'Luz.',
  text: 'La luz fuerte que roza a lo largo de una pared o un techo —una ventana al final del día o una lámpara montada directamente sobre la superficie— deja ver pequeñas diferencias en cualquier superficie reparada, incluidas las nuestras. Juzgamos una reparación como la juzga el oficio de la pintura: a tres pies de distancia, con la luz normal del cuarto. Si una superficie es de las que siempre van a mostrar un parche con esa luz, se lo decimos antes de empezar, no después.',
};

/* road CO (2026-09-26) · A CHANGE ORDER'S PAGE — the job needs more than the quote covered, and nothing extra is bought
   or done until they OK it here. Its own table, apart from WORDS (the quote page's strings, which suite I walks one by
   one). What, why, the price and the new total; their name typed as the signature; or "No thanks". No materials figure
   (R38: the change carries one price), no contact detail, neither of R33's two words. */
export const CHANGE_WORDS = {
  en: {
    title: 'A change to your job · Umbra Domus',
    h1: 'A change to your job',
    lead_name: 'Hi {name}, the job needs a little more than the quote covered.',
    lead: 'Hi, the job needs a little more than the quote covered.',
    nothing_yet: 'Nothing extra is bought or done until you OK it.',
    lbl: 'Change {n}',
    more: '{price} more',
    lbl_total: 'New total',
    was: 'Your quote was {base}',
    h_adds: 'What it adds',
    adds_hint_one: '1 thing · tap to see it',
    adds_hint: '{n} things · tap to see them',
    /* road MW: the work first, and when it happens; the store items only under a fold */
    work_hint_one: '1 step · done during your booked visits',
    work_hint: '{n} steps · done during your booked visits',
    h_items: 'What it uses',
    items_hint_one: '1 item · tap to see it',
    items_hint: '{n} items · tap to see them',
    sign_label: 'Type your name to OK it',
    sign_hint: 'Your name and the time are kept as your written OK.',
    sign_error: 'Type your name to OK the change.',
    ok: 'OK the change',
    no: 'No thanks',
    no_small: 'Then the job is finished as quoted, at the quoted price.',
    h_ok: "Change OK'd.",
    ok_lead: 'Thank you, {name}. Drew picks up what it needs and keeps going.',
    ok_small: "OK'd by {name} · {at}",
    h_no: 'No change.',
    no_lead: 'Got it. The job is finished as quoted, at the quoted price.',
    h_withdrawn: 'This change was withdrawn.',
    withdrawn: 'Reply to our text with any questions.',
    questions: 'Questions? Reply to our text.',
  },
  es: {
    title: 'Un cambio a su trabajo · Umbra Domus',
    h1: 'Un cambio a su trabajo',
    lead_name: 'Hola, {name}: el trabajo necesita un poco más de lo que cubría la cotización.',
    lead: 'Hola: el trabajo necesita un poco más de lo que cubría la cotización.',
    nothing_yet: 'No compramos ni hacemos nada extra hasta que usted lo apruebe.',
    lbl: 'Cambio {n}',
    more: '{price} más',
    lbl_total: 'Nuevo total',
    was: 'Su cotización era de {base}',
    h_adds: 'Lo que agrega',
    adds_hint_one: '1 cosa · toque para verla',
    adds_hint: '{n} cosas · toque para verlas',
    work_hint_one: '1 paso · se hace durante sus visitas ya agendadas',
    work_hint: '{n} pasos · se hacen durante sus visitas ya agendadas',
    h_items: 'Lo que usa',
    items_hint_one: '1 artículo · toque para verlo',
    items_hint: '{n} artículos · toque para verlos',
    sign_label: 'Escriba su nombre para aprobarlo',
    sign_hint: 'Guardamos su nombre y la hora como su aprobación por escrito.',
    sign_error: 'Escriba su nombre para aprobar el cambio.',
    ok: 'Aprobar el cambio',
    no: 'No, gracias',
    no_small: 'Entonces terminamos el trabajo como se cotizó, al precio cotizado.',
    h_ok: 'Cambio aprobado.',
    ok_lead: 'Gracias, {name}. Drew consigue lo necesario y sigue adelante.',
    ok_small: 'Aprobado por {name} · {at}',
    h_no: 'Sin cambio.',
    no_lead: 'Entendido. Terminamos el trabajo como se cotizó, al precio cotizado.',
    h_withdrawn: 'Este cambio fue retirado.',
    withdrawn: 'Responda a nuestro mensaje si tiene preguntas.',
    questions: '¿Preguntas? Responda a nuestro mensaje.',
  },
};
