/* THE CUSTOMER'S PAGE — ITS WORDS (ACCEPT-PAGE-02). Kept apart from page.js so the tests can read the same
   table the page renders from (page.js imports the book; this file imports nothing). */

/* Every fixed string on the page, in both languages. The Spanish is ours; every line goes to his local reviewer
   in the close, with its English beside it. {x} is filled in; nothing else is. No phone number, address or email
   of anyone; nothing R37 §5 rules out of a scheduling message; no materials (R38); neither of the two words R33
   keeps off everything this company prints. Suite I greps every page it renders for all of it. */
export const WORDS = {
  en: {
    title: 'Your quote from Umbra Domus',
    hi_name: 'Hi {name},',
    hi: 'Hi,',
    h_work: "What we'll do",
    h_price: 'Price',
    h_when: 'When',
    when: '{day} · arrival between {window}',
    pick_legend: 'Pick your time',
    pick_error: 'Pick one of the times.',
    hold_one: "We're holding this time for you until {at}.",
    hold_two: "We're holding these times for you until {at}.",
    hold_ended_one: "Our hold on this time has ended, but it's still open.",
    hold_ended_two: "Our hold on these times has ended, but they're still open.",
    h_notices: 'Before you accept',
    statute_intro: 'The disclosure statement Texas Property Code §53.255 asks us to give you before you agree to the work:',
    accept: 'Accept & confirm',
    none: 'None of these times work',
    small: 'Accepting books this visit at the price above. Questions? Reply to our text.',
    h_taken: 'That time was just booked.',
    taken_other: 'This time is still open:',
    taken_none: "Reply to our text and we'll find you another time.",
    h_too_close: 'This time is too close for us to prepare.',
    too_close: "Reply to our text and we'll find another.",
    h_booked: "You're booked.",
    booked_window: 'arrival between {window}',
    booked_confirm: "We'll text you to confirm.",
    h_updating: "We're updating this quote.",
    updating: "You'll get a new text from us shortly.",
    h_replaced: 'This quote was replaced.',
    replaced: 'Use the link in our latest text.',
    h_withdrawn: 'This quote was withdrawn.',
    withdrawn: 'Reply to our text with any questions.',
    h_received: 'Got it.',
    received: "We'll text you some other times.",
    h_not_valid: "This link isn't valid.",
    not_valid: 'Check the link in our text, or reply to it.',
    h_forbidden: "This didn't come from our page.",
    forbidden: 'Open the link in our text again, or reply to it.',
    questions: 'Questions? Reply to our text.',
    /* QUOTE-PAGE-03: the new look. `when`, `booked_window` and `title` leave the visible page by design (the day
       and when_line sit on two lines; BOOKED uses when_line; h1_quote is the heading and `title` stays the <title>). */
    h1_quote: 'Your quote',
    steps: ['Received', 'Quoted', 'Scheduled', 'Done'],
    steps_label: 'Where your request stands',
    lbl_visit: 'Your visit',
    when_line: 'Arrival between {window}',
    law_title: 'Your rights under Texas law',
    law_hint: 'Tap to read',
    add_calendar: 'Add to my calendar',
    ics_title: 'Umbra Domus visit (arrival window)',
    ics_desc: 'Arrival between {window}. Questions? Reply to our text.',
  },
  es: {
    title: 'Su cotización de Umbra Domus',
    hi_name: 'Hola, {name}:',
    hi: 'Hola:',
    h_work: 'Lo que haremos',
    h_price: 'Precio',
    h_when: 'Cuándo',
    when: '{day} · llegada entre {window}',
    pick_legend: 'Elija su horario',
    pick_error: 'Elija uno de los horarios.',
    hold_one: 'Le apartamos este horario hasta el {at}.',
    hold_two: 'Le apartamos estos horarios hasta el {at}.',
    hold_ended_one: 'Ya no le estamos apartando este horario, pero sigue disponible.',
    hold_ended_two: 'Ya no le estamos apartando estos horarios, pero siguen disponibles.',
    h_notices: 'Antes de aceptar',
    statute_intro: 'La declaración que la sección 53.255 del Código de Propiedad de Texas nos pide entregarle antes de que acepte el trabajo (el texto de la ley está en inglés):',
    accept: 'Aceptar y confirmar',
    none: 'Ninguno de estos horarios me acomoda',
    small: 'Al aceptar, queda programada esta visita al precio de arriba. ¿Preguntas? Responda a nuestro mensaje de texto.',
    h_taken: 'Ese horario ya se ocupó.',
    taken_other: 'Este horario sigue disponible:',
    taken_none: 'Responda a nuestro mensaje de texto y le buscaremos otro horario.',
    h_too_close: 'Este horario ya está muy cerca para prepararnos.',
    too_close: 'Responda a nuestro mensaje de texto y le buscaremos otro.',
    h_booked: 'Su visita quedó programada.',
    booked_window: 'Llegada entre {window}',
    booked_confirm: 'Le enviaremos un mensaje de texto para confirmar.',
    h_updating: 'Estamos actualizando esta cotización.',
    updating: 'En breve le enviaremos un nuevo mensaje de texto.',
    h_replaced: 'Esta cotización fue reemplazada.',
    replaced: 'Use el enlace de nuestro mensaje de texto más reciente.',
    h_withdrawn: 'Esta cotización fue retirada.',
    withdrawn: 'Si tiene preguntas, responda a nuestro mensaje de texto.',
    h_received: 'Entendido.',
    received: 'Le enviaremos otros horarios por mensaje de texto.',
    h_not_valid: 'Este enlace no es válido.',
    not_valid: 'Revise el enlace de nuestro mensaje de texto o respóndanos.',
    h_forbidden: 'Esto no se envió desde nuestra página.',
    forbidden: 'Vuelva a abrir el enlace de nuestro mensaje de texto o respóndanos.',
    questions: '¿Preguntas? Responda a nuestro mensaje de texto.',
    /* QUOTE-PAGE-03, from Drew's RGV Spanish researcher (Bridge/SUPE/RESEARCH-SPANISH-RGV-2026-09-23/). ics_desc has
       no period after {window}: its "a.m."/"p.m." ends the sentence. */
    h1_quote: 'Su cotización',
    steps: ['Recibido', 'Cotizado', 'Programado', 'Terminado'],
    steps_label: 'En qué paso va su solicitud',
    lbl_visit: 'Su visita',
    when_line: 'Llegada entre {window}',
    law_title: 'Sus derechos según la ley de Texas',
    law_hint: 'Toque para leer',
    add_calendar: 'Agregar a mi calendario',
    ics_title: 'Visita de Umbra Domus (horario de llegada)',
    ics_desc: 'Llegada entre {window} ¿Preguntas? Responda a nuestro mensaje de texto.',
  },
};

/* READY-4's lighting paragraph, in Spanish (ours — for his reviewer). The English is notices.js, word for word. */
export const LIGHTING_ES = {
  lead: 'Luz.',
  text: 'La luz fuerte que roza a lo largo de una pared o un techo —una ventana al final del día o una lámpara montada directamente sobre la superficie— deja ver pequeñas diferencias en cualquier superficie reparada, incluidas las nuestras. Juzgamos una reparación como la juzga el oficio de la pintura: a tres pies de distancia, con la luz normal del cuarto. Si una superficie es de las que siempre van a mostrar un parche con esa luz, se lo decimos antes de empezar, no después.',
};
